# Here’s an example of a two-service setup where a database’s data directory 
# is shared with another service as a volume so that it can be 
# periodically backed up:
version: "3"

services:
  db:
    image: db
    volumes:
      - data-volume:/var/lib/db
  backup:
    image: backup-service
    volumes:
      - data-volume:/var/lib/backup/data

volumes:
  data-volume:
